### ISSUE TITLE
KeyError at solver.net.blobs['ground_truth'].data[...] = fix_img_to_process

### ISSUE THREAD

**Issue by amarknair** [CLT29/OpenSALICON#1]
Hi everyone,

I am a caffe beginner. When I tried training network myself with OSIE dataset(by running finetune_salicon.py), I am getting the following error. 

**File "finetune_salicon.py", line 75, in <module>
    solver.net.blobs['ground_truth'].data[...] = fix_img_to_process
KeyError: 'ground_truth'**

Can anyone help me out?

**Comment by CLT29** [comment]
Hello,
So, you are trying to train the network for yourself? I have made some updates today so you may want to pull down the new version.
First, please confirm you are able to run the Salicon.py code to extract a map (you can save the image to your computer and verify that it works).
Once you verify that that works, move on to training. Make sure that in the solver.prototxt you are using that you are using the finetune_salicon.prototxt and not the salicon.prototxt (salicon.prototxt does not contain the ground_truth field).
Please confirm that you are using the correct finetune_salicon.prototxt file.
If you are, please attach your modified finetune_salicon.prototxt file, the solver.prototxt file you are using, and the finetune_salicon.py code you have modified and I will take a look.
Thanks!

**Comment by amarknair** [comment]
Thank you for the quick response. I will try it out and let you know.

**Comment by amarknair** [comment]
@CLT29 It started working. I downloaded the latest version. I was able to run Salicon.py successfully and train the model. Thank you for the guidance.
